import BlogKeywords from "@/components/Blog/BlogKeywords";

const keywords = [
  "on grid solar system India", "off grid solar system India", "on grid vs off grid solar",
  "grid tied solar system", "off grid solar power system", "solar system with battery backup",
  "net metering India", "on grid solar system price", "off grid solar system price India",
  "on grid solar inverter", "off grid solar inverter", "hybrid solar system India",
  "solar battery storage India", "on grid solar for home", "off grid solar for home India",
  "solar power for rural India", "grid connected solar system", "solar without battery India",
  "best solar system for home India", "on grid solar system 3kw", "off grid solar 5kw price",
  "solar system with net metering", "solar energy India", "rooftop solar India",
  "solar panel system India", "solar system for home price", "solar power plant India",
  "solar energy for homes", "solar installation India", "renewable energy India",
];

const OnGridVsOffGridSolarIndia = () => {
  return (
    <div>
      <p>
        Choosing between on-grid and off-grid solar systems can be confusing. Let&apos;s explore the key differences, advantages, and applications in the Indian context.
      </p>

      <h2>What is On-Grid Solar?</h2>
      <p>
        On-grid solar systems are connected to the main electricity grid. Excess power generated by your solar panels is fed back into the grid, allowing you to earn credits or reduce your electricity bill through net metering.
      </p>

      <h2>Benefits of On-Grid Solar</h2>
      <ul>
        <li>Lower initial cost  -  no batteries needed</li>
        <li>Net metering: sell excess power back to DISCOM</li>
        <li>Eligible for PM Surya Ghar government subsidy</li>
        <li>Ideal for cities with reliable grid supply</li>
      </ul>

      <h2>What is Off-Grid Solar?</h2>
      <p>
        Off-grid solar systems operate independently from the utility grid, using battery storage to power your home during the night or on cloudy days. They are ideal for rural areas or locations with frequent power cuts.
      </p>

      <h2>Advantages of Off-Grid Solar</h2>
      <ul>
        <li>Complete energy independence from the grid</li>
        <li>Power in remote locations without grid access</li>
        <li>Reliable backup during long outages</li>
        <li>No electricity bill at all (when sized correctly)</li>
      </ul>

      <h2>On-Grid vs Off-Grid: Cost Comparison</h2>
      <p>
        An on-grid 3kW system in India costs approximately ₹1,32,000 after subsidy. An equivalent off-grid system with battery storage can cost ₹2,50,000–₹3,50,000 due to the battery bank. For urban homes in UP with a stable grid, on-grid is almost always the better financial choice.
      </p>

      <h2>Which One to Choose?</h2>
      <p>
        For most urban Indian homes and businesses  -  especially in Lucknow and UP  -  on-grid systems are cost-effective and practical. Off-grid systems suit rural areas, farms, or places with unreliable grid power. A hybrid system (on-grid + battery backup) is a good middle ground if you want both net metering savings and backup power.
      </p>

      <BlogKeywords keywords={keywords} />
    </div>
  );
};

export default OnGridVsOffGridSolarIndia;
