const OnGridVsOffGridSolarIndia = () => {
  return (
    <div>
      <p>
        Choosing between on-grid and off-grid solar systems can be confusing. Let’s explore the key differences, advantages, and applications in the Indian context.
      </p>

      <h2>What is On-Grid Solar?</h2>
      <p>
        On-grid solar systems are connected to the main electricity grid. Excess power generated by your solar panels is fed back into the grid, allowing you to earn credits or reduce your electricity bill.
      </p>

      <h2>Benefits of On-Grid Solar</h2>
      <ul>
        <li>Lower initial cost</li>
        <li>No need for battery storage</li>
        <li>Net metering benefits</li>
      </ul>

      <h2>What is Off-Grid Solar?</h2>
      <p>
        Off-grid solar systems operate independently from the utility grid, usually with battery storage to store excess energy for nighttime or cloudy days.
      </p>

      <h2>Advantages of Off-Grid Solar</h2>
      <ul>
        <li>Power in remote locations without grid access</li>
        <li>Complete energy independence</li>
        <li>Backup power during outages</li>
      </ul>

      <h2>Which One to Choose?</h2>
      <p>
        For most urban Indian homes and businesses, on-grid systems are cost-effective and practical. Off-grid systems suit rural areas or places with unreliable grid power.
      </p>
    </div>
  );
};

export default OnGridVsOffGridSolarIndia;
