import { Blog } from "@/types/blog";

const blogData: Blog[] = [
  {
    id: 35,
    title: "Solar for Warehouses and Godowns in UP 2026: Cut Electricity Bills by 60-80 Percent with Rooftop Solar",
    paragraph:
      "Warehouses and godowns in Lucknow, Kanpur, Barabanki, and across UP pay UPPCL commercial tariffs of Rs 7-9 per unit, and their large flat rooftops are ideal for solar. A correctly sized system on a 100,000 sq ft warehouse can install 200-500 kW, slash electricity costs by 60-80 percent, and claim 40 percent accelerated depreciation in year one, recovering the full investment in four to six years.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["warehouse solar", "godown solar", "UP solar"],
    publishDate: "September 2026",
    slug: "solar-for-warehouses-up-2026",
    readTime: "8 min read",
  },
  {
    id: 34,
    title: "Solar for Petrol Pumps and Fuel Stations in UP 2026: Cut Bills, Ditch the Generator, and Pay Back in 4-5 Years",
    paragraph:
      "A mid-sized petrol pump in UP pays Rs 40,000 to Rs 80,000 per month on UPPCL commercial electricity plus Rs 15,000 to Rs 40,000 in diesel generator costs. A correctly sized rooftop or canopy-mounted solar system can cut total energy costs by 40 to 70 percent, qualify for 40 percent accelerated depreciation, and pay back in four to five years. Here is a complete guide for petrol pump and CNG station operators in Lucknow, Kanpur, Unnao, Barabanki, Sitapur, and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["petrol pump solar", "fuel station", "UP solar"],
    publishDate: "September 2026",
    slug: "solar-for-petrol-pumps-up",
    readTime: "8 min read",
  },
  {
    id: 33,
    title: "Solar for Hotels and Restaurants in UP 2026: Cut Electricity Bills by 50-70 Percent and Recover Costs in 4-5 Years",
    paragraph:
      "Hotels and restaurants in UP pay UPPCL commercial tariffs of Rs 7-9 per unit, with monthly bills ranging from Rs 30,000 to Rs 5 lakh or more for large properties. A correctly sized rooftop solar system can cut that bill by 50 to 70 percent, and 40 percent accelerated depreciation in the first year makes the investment highly attractive for hospitality businesses in Lucknow, Kanpur, Ayodhya, and Raebareli in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["hotels", "restaurants", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-for-hotels-restaurants-up",
    readTime: "8 min read",
  },
  {
    id: 32,
    title: "Solar for Factories and Industrial Units in UP 2026: Cut Bills by 60-80 Percent with Rooftop Solar",
    paragraph:
      "Factories in Lucknow, Kanpur, Unnao, and Raebareli pay Rs 7-9 per unit to UPPCL, with monthly bills ranging from Rs 2.5 lakh to Rs 10 lakh or more. A correctly sized rooftop solar system can cut that cost by 60 to 80 percent, and 40 percent accelerated depreciation makes the investment even more attractive for industrial units in Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["factory solar", "industrial solar", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-for-factories-up",
    readTime: "8 min read",
  },
  {
    id: 31,
    title: "Solar Energy for Dairy Farms in UP 2026: Cut Electricity Bills, Protect Milk, and Pay Back in 4-5 Years",
    paragraph:
      "UP dairy farms pay Rs 7-9 per unit to UPPCL for chillers, pumps, and processing equipment, and many lose milk to power cuts every year. A properly sized rooftop or ground-mounted solar system can cover 70-90 percent of daytime dairy electricity consumption, eliminate two to four hours of diesel generator runtime per day, and pay back in four to five years. Here is a practical guide for dairy operators in Lucknow, Kanpur, Barabanki, Unnao, and Sitapur in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["dairy farm solar", "UP solar", "agri solar"],
    publishDate: "August 2026",
    slug: "solar-for-dairy-farms-up",
    readTime: "8 min read",
  },
  {
    id: 30,
    title: "Solar for Hospitals and Clinics in UP 2026: Cut Bills, Reduce Diesel Dependency, and Recover Costs in 4-6 Years",
    paragraph:
      "Hospitals and clinics in UP pay Rs 1.5 lakh to Rs 4 lakh per month on UPPCL commercial electricity at Rs 7-9 per unit, plus heavy diesel generator costs for backup. A correctly sized rooftop solar system with optional battery backup can cut these costs by 40-70 percent, qualify for 40 percent accelerated depreciation, and pay back in four to six years. Here is a complete guide for healthcare facilities in Lucknow, Kanpur, Ayodhya, Raebareli, and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["hospitals", "clinics", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-for-hospitals-clinics-up",
    readTime: "8 min read",
  },
  {
    id: 29,
    title: "Solar for Housing Societies in UP 2026: How RWAs Can Cut Common Area Bills by 80 Percent",
    paragraph:
      "Housing societies in Lucknow, Kanpur, and across UP pay Rs 10,000 to Rs 1,00,000 per month on common area electricity for lifts, water pumps, and corridor lighting. A rooftop solar system on the society terrace can cut that bill by 60 to 90 percent, reduce every resident's maintenance levy, and pay back its cost in 4-5 years. Here is a complete guide for RWAs planning a solar project in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["housing society", "RWA solar", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-for-housing-societies-up",
    readTime: "8 min read",
  },
  {
    id: 28,
    title: "Solar for Cold Storage in UP 2026: How to Cut Your Electricity Bill by 40-70 Percent",
    paragraph:
      "Cold storage operators in UP pay Rs 1 lakh to Rs 2.25 lakh per month on UPPCL electricity bills. A properly sized rooftop solar system can slash this by 40 to 70 percent while accelerated depreciation and net metering stack up further savings. Here is a practical guide to sizing, costs, financial benefits, and installation considerations for cold storage units in Lucknow, Barabanki, Sitapur, and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["cold storage", "commercial solar", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-cold-storage-up",
    readTime: "8 min read",
  },
  {
    id: 27,
    title: "Solar Power for Air Conditioners in Lucknow 2026: System Sizing, Costs, and Real Savings",
    paragraph:
      "Air conditioners are now a necessity across UP, and a single 1.5-ton AC can add Rs 1,700 to Rs 2,700 to your UPPCL bill every summer month. Here is how rooftop solar in Lucknow and neighbouring cities can cover your AC load almost unit for unit, with real savings numbers, sizing guidance, and PM Surya Ghar subsidy details for 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar AC", "summer savings", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-ac-lucknow",
    readTime: "7 min read",
  },
  {
    id: 26,
    title: "Solar vs Diesel Generator in Lucknow 2026: Which Backup Power Solution Actually Saves You Money?",
    paragraph:
      "Diesel generators in UP cost Rs 18-25 per unit to run once fuel and maintenance are included. A hybrid solar system with battery backup delivers the same outage protection for a fraction of that, while also cutting your regular UPPCL bill. Here is the honest cost comparison for homes and businesses in Lucknow and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar vs generator", "backup power", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-vs-generator-lucknow",
    readTime: "7 min read",
  },
  {
    id: 25,
    title: "Solar EV Charging in UP 2026: How to Power Your Electric Vehicle with Rooftop Solar",
    paragraph:
      "Electric vehicles are multiplying on UP roads, and combining rooftop solar with home EV charging is one of the most effective ways to cut both your electricity bill and your monthly fuel cost together. Here is a practical guide to sizing, savings, costs, and setup for EV owners in Lucknow, Kanpur, and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar EV charging", "electric vehicle", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-ev-charging-up",
    readTime: "7 min read",
  },
  {
    id: 24,
    title: "Solar Rooftop vs Ground Mount in UP 2026: Which Installation Type Is Right for Your Property?",
    paragraph:
      "Most solar installations in Lucknow and UP go on rooftops, but property owners with open land, farmhouses, or shaded roofs sometimes consider ground-mounted systems. Here is a practical comparison of costs, performance, subsidy eligibility, and UPPCL rules to help you choose the right mounting type for your home or business in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["rooftop solar", "ground mount", "UP installation"],
    publishDate: "August 2026",
    slug: "solar-rooftop-vs-ground-mount",
    readTime: "7 min read",
  },
  {
    id: 23,
    title: "Hybrid Solar System in India 2026: How UP Homes Can Get Backup Power and Cut Bills Together",
    paragraph:
      "A hybrid solar system combines solar panels, battery storage, and a smart inverter to keep your home powered during UPPCL outages while maximising bill savings through net metering. Here is a practical guide to costs, battery options, subsidy eligibility, and when hybrid makes more sense than a standard on-grid system for homes and businesses in Lucknow and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["hybrid solar", "battery backup", "UP"],
    publishDate: "August 2026",
    slug: "hybrid-solar-system-india",
    readTime: "7 min read",
  },
  {
    id: 22,
    title: "Solar Panel Lifespan in India: How Long Do Your Panels Actually Last?",
    paragraph:
      "Most quality solar panels installed today will produce usable electricity for 25 to 30 years, but the actual lifespan depends on brand, UP climate conditions, installation quality, and maintenance. This guide covers degradation rates, warranty types, what heatwaves and dust do to panels in Lucknow and across Uttar Pradesh, and when replacement makes financial sense in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar panel lifespan", "UP solar", "panel warranty"],
    publishDate: "August 2026",
    slug: "solar-panel-lifespan-india",
    readTime: "7 min read",
  },
  {
    id: 21,
    title: "Solar for Schools and Colleges in UP 2026: How Educational Institutions Can Cut Costs and Go Green",
    paragraph:
      "Schools and colleges in UP pay commercial electricity tariffs of Rs 7-9 per unit, and their daytime operating hours align perfectly with peak solar generation. Here is a complete guide to system sizing, net metering under UPPCL, tax benefits, and subsidies for educational institutions in Lucknow and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["schools", "colleges", "UP solar"],
    publishDate: "August 2026",
    slug: "solar-for-schools-colleges-up",
    readTime: "7 min read",
  },
  {
    id: 20,
    title: "Solar Subsidy in UP 2026: How to Apply Under UPPCL and PM Surya Ghar Step by Step",
    paragraph:
      "The PM Surya Ghar scheme offers up to Rs 78,000 central subsidy on rooftop solar in UP, yet many eligible homeowners in Lucknow, Kanpur, and across Uttar Pradesh have not applied because the process seems complex. This step-by-step guide covers registration, DISCOM approval, installer selection, net metering, and how the subsidy reaches your bank account in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar subsidy", "UPPCL", "PM Surya Ghar"],
    publishDate: "July 2026",
    slug: "solar-subsidy-apply-uppcl-2026",
    readTime: "7 min read",
  },
  {
    id: 19,
    title: "Solar Savings in Lucknow 2026: How Much Can Your Home or Business Actually Save?",
    paragraph:
      "A 5 kW rooftop solar system in Lucknow generates around 600 units per month and can cut your LESCO electricity bill by Rs 4,200 to Rs 5,400 every month. Here is a practical breakdown of real savings by system size, net metering benefits, and payback periods for homes and businesses across Lucknow and UP in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar savings", "Lucknow", "UP"],
    publishDate: "July 2026",
    slug: "solar-savings-lucknow",
    readTime: "7 min read",
  },
  {
    id: 18,
    title: "Commercial Solar Rooftop in UP 2026: How Businesses Cut Costs and Qualify for Subsidies",
    paragraph:
      "Commercial electricity in UP costs Rs 7-9 per unit in 2026. Here is how factories, offices, hotels, and retail businesses in Lucknow and across Uttar Pradesh can cut bills by 70-90 percent with rooftop solar, UPPCL net metering, and accelerated depreciation benefits.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["commercial solar", "UP", "net metering"],
    publishDate: "July 2026",
    slug: "commercial-solar-rooftop-up",
    readTime: "7 min read",
  },
  {
    id: 17,
    title: "Solar Panel EMI and Financing in India 2026: How to Go Solar Without Paying Upfront in UP",
    paragraph:
      "A 3 kW solar system in UP costs around Rs 1.5 lakh after PM Surya Ghar subsidy. With the right EMI plan, your monthly loan payment can be lower than your current electricity bill from day one. Here is a complete guide to solar financing options for homeowners in Lucknow and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar EMI", "financing", "UP"],
    publishDate: "July 2026",
    slug: "solar-emi-financing-india",
    readTime: "7 min read",
  },
  {
    id: 16,
    title: "Solar Inverter Buying Guide for India 2026: Types, Brands, and What to Look For in UP",
    paragraph:
      "The inverter is the brain of your solar system, yet most buyers treat it as an afterthought. This practical guide covers inverter types, key specs, top brands, price ranges, and what matters most for homes and businesses in Lucknow and across Uttar Pradesh in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar inverter", "buying guide", "UP"],
    publishDate: "July 2026",
    slug: "solar-inverter-buying-guide-india",
    readTime: "7 min read",
  },
  {
    id: 15,
    title: "PM KUSUM Solar Pump Scheme in UP 2026: Subsidy, Eligibility and How to Apply",
    paragraph:
      "UP farmers can replace diesel irrigation pumps with solar at up to 60 percent subsidy under PM KUSUM. Here is a complete guide to eligibility, costs, UPNEDA application process, and the real savings over diesel in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["PM KUSUM", "solar pump", "UP farmers"],
    publishDate: "July 2026",
    slug: "pm-kusum-solar-pump-up",
    readTime: "7 min read",
  },
  {
    id: 14,
    title: "Solar Panel Performance in North India Winters: What UP Homeowners Need to Know",
    paragraph:
      "Dense fog, shorter days, and cold temperatures all affect rooftop solar in Lucknow and across UP from December to February. Here is exactly what to expect from your system in winter - and why the numbers are better than most people fear.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["winter solar", "North India", "UP performance"],
    publishDate: "July 2026",
    slug: "solar-performance-winter-north-india",
    readTime: "7 min read",
  },
  {
    id: 13,
    title: "Solar for Apartments in India: How Flat Owners in UP Can Go Solar in 2026",
    paragraph:
      "Living in a flat doesn't mean you're locked out of solar. This guide explains how apartment residents in Lucknow, Kanpur, and across UP can use group net metering, housing society installations, and PM Surya Ghar subsidy to cut their electricity bills in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["apartments", "group net metering", "UP"],
    publishDate: "July 2026",
    slug: "solar-for-apartments-india",
    readTime: "7 min read",
  },
  {
    id: 12,
    title: "Net Metering in UP 2026: How to Apply Under UPPCL and Maximise Your Solar Savings",
    paragraph:
      "Net metering lets rooftop solar owners in Uttar Pradesh export surplus power to the UPPCL grid and earn credits against future bills. Here is a complete step-by-step guide to applying, understanding your bill, and getting the most from your solar investment in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["net metering", "UPPCL", "Lucknow"],
    publishDate: "July 2026",
    slug: "net-metering-guide-uppcl",
    readTime: "7 min read",
  },
  {
    id: 11,
    title: "Solar Battery Storage in India 2026: Do You Really Need a Battery with Your Solar System?",
    paragraph:
      "Battery storage adds resilience and evening energy independence to your rooftop solar setup - but it is not always the right investment. Here is how to decide for UP homes and businesses in 2026.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["battery storage", "hybrid solar", "UP"],
    publishDate: "July 2026",
    slug: "solar-battery-storage-india-2026",
    readTime: "7 min read",
  },
  {
    id: 10,
    title: "Solar for Small Businesses in UP: Savings, Net Metering, and Tax Benefits Explained",
    paragraph:
      "Commercial electricity in UP costs Rs 7-9 per unit in 2026. Here is how small businesses in Lucknow and across Uttar Pradesh can cut bills by 70-90 percent with rooftop solar, net metering, and smart tax planning.",
    image: "",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["small business", "UP", "commercial solar"],
    publishDate: "July 2026",
    slug: "solar-for-small-businesses-up",
    readTime: "7 min read",
  },
  {
    id: 9,
    title: "PM Surya Ghar Muft Bijli Yojana 2026  -  Complete Guide for Indian Homeowners",
    paragraph:
      "India's biggest rooftop solar scheme offers up to ₹78,000 subsidy and 300 units of free electricity per month. Here's everything you need to know to apply in 2026.",
    image: "/images/blog/surya_yojna.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Policy Analyst",
    },
    tags: ["government scheme", "subsidy", "2026"],
    publishDate: "June 2026",
    slug: "pm-surya-ghar-yojana-2026",
    readTime: "7 min read",
  },
  {
    id: 8,
    title: "Best Solar Panels in India 2026 - Top Brands Compared (Waaree, Adani, Tata & More)",
    paragraph:
      "A clear, unbiased comparison of the best solar panel brands available in India  -  from Waaree and Adani to Jinko and LONGi  -  to help you choose the right panels for your home or business.",
    image: "/images/blog/solar_brands.png",
    author: {
      name: "Rishi",
      image: "/images/blog/author.jpg",
      designation: "Solar Technology Expert",
    },
    tags: ["solar panels", "brands", "comparison"],
    publishDate: "May 2026",
    slug: "best-solar-panels-india-2026",
    readTime: "8 min read",
  },
  {
    id: 7,
    title: "Solar Panel Maintenance Guide for Indian Homes - Keep Your System at Peak Output",
    paragraph:
      "Everything you need to know about maintaining your solar panels in India's dust, heat, and monsoon conditions  -  cleaning schedules, inverter checks, and AMC costs explained.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Sneha Kapoor",
      image: "/images/blog/author.jpg",
      designation: "Energy Systems Engineer",
    },
    tags: ["maintenance", "tips", "performance"],
    publishDate: "May 2026",
    slug: "solar-panel-maintenance-india",
    readTime: "6 min read",
  },
  {
    id: 6,
    title: "Solar Panel Price in Lucknow 2026: Complete Guide with UP Subsidy",
    paragraph:
      "Everything you need to know about solar panel costs in Lucknow  -  system sizes, UP government subsidy slabs, top installers, and how to get the best deal in 2026.",
    image: "/images/blog/solar_panel_pricing.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["lucknow", "pricing", "subsidy"],
    publishDate: "April 2026",
    slug: "solar-panel-price-lucknow-guide",
    readTime: "5 min read",
  },
  {
    id: 1,
    title: "How to Choose Between On-Grid and Off-Grid Solar Systems in India",
    paragraph:
      "Confused between on-grid and off-grid solar? We break down the pros, cons, and ideal use cases for Indian homes and businesses.",
    image: "/images/blog/offgrid_ongrid.jpg",
    author: {
      name: "Rishi",
      image: "/images/blog/author.jpg",
      designation: "Solar Consultant",
    },
    tags: ["solar", "grid", "india"],
    publishDate: "2026",
    slug: "on-grid-vs-off-grid-solar-india",
    readTime: "5 min read",
  },
  {
    id: 2,
    title: "Top Government Solar Subsidy Schemes in India (2026 Guide)",
    paragraph:
      "Maximize your solar investment by taking advantage of India's latest rooftop solar subsidies and state-wise incentives.",
    image: "/images/blog/solar_subsidy.png",
    author: {
      name: "Ravi Sharma",
      image: "/images/blog/author.jpg",
      designation: "Policy Analyst",
    },
    tags: ["policy", "subsidy", "savings"],
    publishDate: "2026",
    slug: "solar-subsidy-schemes-india-2026",
    readTime: "6 min read",
  },
  {
    id: 3,
    title: "How Much Can You Save with a Solar Power Plant?",
    paragraph:
      "A practical breakdown of savings for homeowners, businesses, and factories using real solar ROI examples from India.",
    image: "/images/blog/solar_savings.png",
    author: {
      name: "Sneha Kapoor",
      image: "/images/blog/author.jpg",
      designation: "Energy Analyst",
    },
    tags: ["savings", "finance", "roi"],
    publishDate: "2026",
    slug: "solar-power-plant-savings-india",
    readTime: "5 min read",
  },
  {
    id: 4,
    title: "Solar Water Heaters vs Electric Geysers: What's Better in 2026?",
    paragraph:
      "Compare solar thermal systems with electric geysers in terms of cost, performance, and long-term impact for Indian homes.",
    image: "/images/blog/solar-water-heater.webp",
    author: {
      name: "Dr. Nikhil Verma",
      image: "/images/blog/author.jpg",
      designation: "Sustainability Expert",
    },
    tags: ["solar water", "heating", "comparison"],
    publishDate: "2026",
    slug: "solar-water-heaters-vs-electric-geysers-2026",
    readTime: "5 min read",
  },
  {
    id: 5,
    title: "Solar for Agriculture: Is It Worth It for Indian Farmers?",
    paragraph:
      "Explore how solar water pumps and irrigation systems are revolutionizing farming in rural India, with government support.",
    image: "/images/blog/solar-agriculture.jpg",
    author: {
      name: "Rishi",
      image: "/images/blog/author.jpg",
      designation: "Agri-Tech Writer",
    },
    tags: ["agriculture", "solar pump", "rural"],
    publishDate: "2026",
    slug: "solar-for-agriculture-indian-farmers",
    readTime: "5 min read",
  },
];

export default blogData;
